<?php
namespace Database\Seeders;

use App\Models\AgeRange;
use App\Models\Category;
use App\Models\Game;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $age_ranges = ['6-10', '10-13', '13-16'];
        foreach ($age_ranges as $index => $age_range) {
            AgeRange::create([
                'sort_order' => $index + 1,
                'slug'       => Str::slug($age_range),
                'name'       => $age_range,
            ]);
        }

        $categories = ['Maths', 'English', 'Biology', 'Chemistry', 'Physics', 'Earth & Space', 'Science Lab', 'History', 'Geography'];
        foreach ($categories as $index => $category) {
            Category::create([
                'sort_order' => $index + 1,
                'slug'       => Str::slug($category),
                'name'       => $category,
            ]);
        }

        $games = [[
            'SortOrder' => 1,
            'Category' => 'Maths',
            'Name'     => 'Addition',
            'Icon'     => 'bi bi-plus-circle',
            'AgeRange' => '6-10',
            'Blurb'    => 'Test your addition skills with this fun and interactive game. Solve addition problems and improve your math abilities while having a great time!',
        ], [
            'SortOrder' => 2,
            'Category' => 'Maths',
            'Name'     => 'Subtraction',
            'Icon'     => 'bi bi-dash-circle',
            'AgeRange' => '6-10',
            'Blurb'    => 'Test your subtraction skills with this fun and interactive game. Solve subtraction problems and improve your math abilities while having a great time!',
        ], [
            'SortOrder' => 3,
            'Category' => 'Maths',
            'Name'     => 'Multiplication',
            'Icon'     => 'bi bi-x-circle',
            'AgeRange' => '6-10',
            'Blurb'    => 'Test your multiplication skills with this fun and interactive game. Solve multiplication problems and improve your math abilities while having a great time!',
        ], [
            'SortOrder' => 4,
            'Category' => 'Maths',
            'Name'     => 'Division',
            'Icon'     => 'bi bi-slash-circle',
            'AgeRange' => '6-10',
            'Blurb'    => 'Test your division skills with this fun and interactive game. Solve division problems and improve your math abilities while having a great time!',
        ], [
            'SortOrder' => 5,
            'Category' => 'Maths',
            'Name'     => 'Mixed Operations',
            'Slug'     => 'mixed',
            'Icon'     => 'bi bi-shuffle',
            'AgeRange' => '6-10',
            'Blurb'    => 'A mixed maths practice game that blends adding, subtracting, multiplying and dividing in one round — choose which operations and numbers to include.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Number Bonds',
            'Icon'     => 'bi bi-link-45deg',
            'AgeRange' => '6-10',
            'Blurb'    => 'Free number bonds game — find the missing number needed to make 10, 20 or 100.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Telling the Time',
            'Slug'     => 'telling-time',
            'Icon'     => 'bi bi-clock',
            'AgeRange' => '6-10',
            'Blurb'    => 'Learn to read a clock face in this free game — match the analogue time shown to the correct digital time.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Money & Coins',
            'Icon'     => 'bi bi-cash-coin',
            'AgeRange' => '6-10',
            'Blurb'    => 'Free money game — count up coins to find the total, or work out the change from a purchase.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Shape Recognition',
            'Icon'     => 'bi bi-pentagon',
            'AgeRange' => '6-10',
            'Blurb'    => 'Free shape game — name 2D and 3D shapes, or count their sides.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Skip Counting',
            'Icon'     => 'bi bi-sort-numeric-up',
            'AgeRange' => '6-10',
            'Blurb'    => 'Free skip counting game — count on in 2s, 5s and 10s, and find the missing number in a sequence.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Fractions & Decimals',
            'Slug'     => 'fractions',
            'Icon'     => 'bi bi-pie-chart',
            'AgeRange' => '10-13',
            'Blurb'    => 'A free fractions and decimals game covering comparing fractions, converting to decimals, and simplifying — great for building number fluency.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Area & Perimeter',
            'Slug'     => 'area-perimeter',
            'Icon'     => 'bi bi-bounding-box',
            'AgeRange' => '10-13',
            'Blurb'    => 'Sharpen shape skills with this free area and perimeter game — choose the shapes and side lengths, then work out the answer.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Volume',
            'Icon'     => 'bi bi-box-seam',
            'AgeRange' => '10-13',
            'Blurb'    => 'Practise 3D shape formulas in this free volume game — pick your shapes and dimensions, then calculate the volume of each one.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Angles',
            'Icon'     => 'bi bi-triangle',
            'AgeRange' => '10-13',
            'Blurb'    => 'Learn to spot angle types fast in this free game — decide whether each one shown is acute, right, obtuse or reflex.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Circles',
            'Icon'     => 'bi bi-circle',
            'AgeRange' => '10-13',
            'Blurb'    => 'Practise circle formulas in this free game — set your own radii, then calculate the circumference or area of each one.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Factors & Multiples',
            'Slug'     => 'factors-multiples',
            'Icon'     => 'bi bi-diagram-3',
            'AgeRange' => '10-13',
            'Blurb'    => 'Free factors and multiples game — find factors, multiples, primes, the HCF and the LCM.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Negative Numbers',
            'Icon'     => 'bi bi-plus-slash-minus',
            'AgeRange' => '10-13',
            'Blurb'    => 'Free negative numbers game — add, subtract and multiply positive and negative numbers.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Coordinates',
            'Icon'     => 'bi bi-bullseye',
            'AgeRange' => '10-13',
            'Blurb'    => 'Free coordinates game — read and plot points, work with all four quadrants, and find missing coordinates.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Sequences',
            'Icon'     => 'bi bi-signpost',
            'AgeRange' => '10-13',
            'Blurb'    => 'Free sequences game — find the next number, spot a missing term, and work out the rule.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Symmetry',
            'Icon'     => 'bi bi-symmetry-vertical',
            'AgeRange' => '10-13',
            'Blurb'    => 'Free symmetry game — find lines of symmetry, spot reflections, and check rotational symmetry.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Percentages',
            'Icon'     => 'bi bi-percent',
            'AgeRange' => '13-16',
            'Blurb'    => 'Free percentages game — find percentages of numbers and work out percentage increase and decrease.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Ratio & Proportion',
            'Slug'     => 'ratio-proportion',
            'Icon'     => 'bi bi-arrow-left-right',
            'AgeRange' => '13-16',
            'Blurb'    => 'Free ratio and proportion game — share amounts in a given ratio, or scale a quantity up or down.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Algebra',
            'Icon'     => 'bi bi-braces',
            'AgeRange' => '13-16',
            'Blurb'    => 'Get to grips with solving equations in this free algebra game — work through one-step and two-step equations to find the value of x.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Standard Form',
            'Icon'     => 'bi bi-123',
            'AgeRange' => '13-16',
            'Blurb'    => 'Practise standard form in this free game — convert numbers to and from standard form, and multiply standard form numbers.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Trigonometry',
            'Icon'     => 'bi bi-rulers',
            'AgeRange' => '13-16',
            'Blurb'    => "A free trigonometry game for GCSE-level practice — use Pythagoras' theorem and SOH-CAH-TOA to find the missing side of a right-angled triangle.",
        ], [
            'Category' => 'Maths',
            'Name'     => 'Simultaneous Equations',
            'Slug'     => 'simultaneous-equations',
            'Icon'     => 'bi bi-intersect',
            'AgeRange' => '13-16',
            'Blurb'    => 'A free simultaneous equations game — solve pairs of linear equations to find matching values of x and y.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Quadratic Equations',
            'Slug'     => 'quadratic-equations',
            'Icon'     => 'bi bi-graph-up',
            'AgeRange' => '13-16',
            'Blurb'    => 'Free quadratic equations game — factorise and solve equations of the form x² + bx + c = 0 to find both roots.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Vectors',
            'Icon'     => 'bi bi-arrow-up-right',
            'AgeRange' => '13-16',
            'Blurb'    => 'Free vectors game covering addition, subtraction and scalar multiplication of column vectors.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Circle Theorems',
            'Slug'     => 'circle-theorems',
            'Icon'     => 'bi bi-compass',
            'AgeRange' => '13-16',
            'Blurb'    => 'Free circle theorems game — use the circle theorem rules to find missing angles on labelled diagrams.',
        ], [
            'Category' => 'Maths',
            'Name'     => 'Probability',
            'Icon'     => 'bi bi-dice-5',
            'AgeRange' => '13-16',
            'Blurb'    => 'Free probability game — work out the probability of single and combined events, and read values from probability tables.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Animal Sorting',
            'Slug'     => 'animal-sorting',
            'Icon'     => 'bi bi-collection',
            'AgeRange' => '6-10',
            'Blurb'    => 'Sort animals into groups — mammals, birds, fish, reptiles and insects.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Life Cycles',
            'Slug'     => 'life-cycles',
            'Icon'     => 'bi bi-arrow-repeat',
            'AgeRange' => '6-10',
            'Blurb'    => 'Put the stages of a frog, butterfly or plant life cycle into the right order.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Body Parts',
            'Slug'     => 'body-parts',
            'Icon'     => 'bi bi-person-badge',
            'AgeRange' => '6-10',
            'Blurb'    => 'Match the names of human body parts to the correct spot on a picture.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Plant Parts',
            'Slug'     => 'plant-parts',
            'Icon'     => 'bi bi-diagram-2',
            'AgeRange' => '6-10',
            'Blurb'    => 'Label the parts of a plant — roots, stem, leaf and flower.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Healthy Eating',
            'Slug'     => 'healthy-eating',
            'Icon'     => 'bi bi-cookie',
            'AgeRange' => '6-10',
            'Blurb'    => 'Sort foods into the right food group and build a balanced plate.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Cell Explorer',
            'Slug'     => 'cell-explorer',
            'Icon'     => 'bi bi-grid-3x3-gap',
            'AgeRange' => '10-13',
            'Blurb'    => 'Identify the parts of a plant or animal cell and what each one does.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Food Chains & Webs',
            'Slug'     => 'food-chains-webs',
            'Icon'     => 'bi bi-diagram-3',
            'AgeRange' => '10-13',
            'Blurb'    => 'Build a correct food chain or food web from producers to predators.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Body Systems',
            'Slug'     => 'body-systems',
            'Icon'     => 'bi bi-link-45deg',
            'AgeRange' => '10-13',
            'Blurb'    => 'Match organs to the body system they belong to — digestive, circulatory and respiratory.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Classification',
            'Slug'     => 'classification',
            'Icon'     => 'bi bi-collection',
            'AgeRange' => '10-13',
            'Blurb'    => 'Sort living things into kingdoms and groups based on their features.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Animal Adaptations',
            'Slug'     => 'animal-adaptations',
            'Icon'     => 'bi bi-compass',
            'AgeRange' => '10-13',
            'Blurb'    => 'Match animals to the habitat and adaptation that helps them survive there.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Genetics & Inheritance',
            'Slug'     => 'genetics-inheritance',
            'Icon'     => 'bi bi-braces-asterisk',
            'AgeRange' => '13-16',
            'Blurb'    => 'Practise Punnett squares to predict dominant and recessive inherited traits.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Photosynthesis & Respiration',
            'Slug'     => 'photosynthesis-respiration',
            'Icon'     => 'bi bi-arrow-left-right',
            'AgeRange' => '13-16',
            'Blurb'    => 'Compare the equations and conditions for photosynthesis and respiration.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Ecosystems & Energy Transfer',
            'Slug'     => 'ecosystems-energy-transfer',
            'Icon'     => 'bi bi-graph-up',
            'AgeRange' => '13-16',
            'Blurb'    => 'Calculate energy transfer between trophic levels in a food chain.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Human Physiology',
            'Slug'     => 'human-physiology',
            'Icon'     => 'bi bi-list-check',
            'AgeRange' => '13-16',
            'Blurb'    => 'Answer questions on homeostasis, enzymes and digestion.',
        ], [
            'Category' => 'Biology',
            'Name'     => 'Evolution & Natural Selection',
            'Slug'     => 'evolution-natural-selection',
            'Icon'     => 'bi bi-clock-history',
            'AgeRange' => '13-16',
            'Blurb'    => 'Work through natural selection scenarios to see how species change over time.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'States of Matter',
            'Slug'     => 'states-of-matter',
            'Icon'     => 'bi bi-droplet-half',
            'AgeRange' => '6-10',
            'Blurb'    => 'Sort everyday things into solids, liquids and gases.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Materials Sort',
            'Slug'     => 'materials-sort',
            'Icon'     => 'bi bi-box-seam',
            'AgeRange' => '6-10',
            'Blurb'    => 'Match everyday objects to the material they are made from — wood, metal, plastic or glass.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Mixing Colours',
            'Slug'     => 'mixing-colours',
            'Icon'     => 'bi bi-palette',
            'AgeRange' => '6-10',
            'Blurb'    => 'Predict what colour you get when you mix two primary colours together.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Floating & Sinking',
            'Slug'     => 'floating-sinking',
            'Icon'     => 'bi bi-circle',
            'AgeRange' => '6-10',
            'Blurb'    => 'Guess whether an object will float or sink, then check the result.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Hot & Cold',
            'Slug'     => 'hot-cold',
            'Icon'     => 'bi bi-sliders',
            'AgeRange' => '6-10',
            'Blurb'    => 'Sort what happens to materials when they are heated or cooled — melting, freezing and more.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Periodic Table Explorer',
            'Slug'     => 'periodic-table-explorer',
            'Icon'     => 'bi bi-table',
            'AgeRange' => '10-13',
            'Blurb'    => 'Match element names to their symbols and position on the periodic table.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Atoms & Molecules',
            'Slug'     => 'atoms-molecules',
            'Icon'     => 'bi bi-diagram-2',
            'AgeRange' => '10-13',
            'Blurb'    => 'Tell the difference between atoms, molecules and compounds.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Acids & Alkalis',
            'Slug'     => 'acids-alkalis',
            'Icon'     => 'bi bi-droplet-half',
            'AgeRange' => '10-13',
            'Blurb'    => 'Use the pH scale and indicator colours to sort acids, alkalis and neutrals.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Separating Mixtures',
            'Slug'     => 'separating-mixtures',
            'Icon'     => 'bi bi-funnel',
            'AgeRange' => '10-13',
            'Blurb'    => 'Pick the right method to separate a mixture — filtration, evaporation or distillation.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Chemical vs Physical Changes',
            'Slug'     => 'chemical-physical-changes',
            'Icon'     => 'bi bi-arrow-left-right',
            'AgeRange' => '10-13',
            'Blurb'    => 'Decide whether a change described is chemical or physical.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Balancing Equations',
            'Slug'     => 'balancing-equations',
            'Icon'     => 'bi bi-braces',
            'AgeRange' => '13-16',
            'Blurb'    => 'Balance chemical equations by adjusting the numbers on each side.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Bonding',
            'Slug'     => 'bonding',
            'Icon'     => 'bi bi-link-45deg',
            'AgeRange' => '13-16',
            'Blurb'    => 'Practise telling ionic bonds apart from covalent bonds.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Rates of Reaction',
            'Slug'     => 'rates-of-reaction',
            'Icon'     => 'bi bi-stopwatch',
            'AgeRange' => '13-16',
            'Blurb'    => 'Work out how temperature, concentration and surface area affect reaction speed.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Moles & Calculations',
            'Slug'     => 'moles-calculations',
            'Icon'     => 'bi bi-calculator',
            'AgeRange' => '13-16',
            'Blurb'    => 'Practise mole calculations using mass, relative formula mass and concentration.',
        ], [
            'Category' => 'Chemistry',
            'Name'     => 'Electrolysis & Reactivity',
            'Slug'     => 'electrolysis-reactivity',
            'Icon'     => 'bi bi-lightning-charge',
            'AgeRange' => '13-16',
            'Blurb'    => 'Use the reactivity series and electrolysis rules to answer questions on each.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Push & Pull',
            'Slug'     => 'push-pull',
            'Icon'     => 'bi bi-arrow-left-right',
            'AgeRange' => '6-10',
            'Blurb'    => 'Decide whether a force shown in a picture is a push or a pull.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Light & Shadows',
            'Slug'     => 'light-shadows',
            'Icon'     => 'bi bi-lightbulb',
            'AgeRange' => '6-10',
            'Blurb'    => 'Predict the size and shape of a shadow made by moving the light source.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Magnets',
            'Slug'     => 'magnets',
            'Icon'     => 'bi bi-link-45deg',
            'AgeRange' => '6-10',
            'Blurb'    => 'Guess which objects a magnet will pick up and which it won\'t.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Sounds Around Us',
            'Slug'     => 'sounds-around-us',
            'Icon'     => 'bi bi-chat-left-text',
            'AgeRange' => '6-10',
            'Blurb'    => 'Sort sounds by loud or quiet, and by high or low pitch.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Simple Machines',
            'Slug'     => 'simple-machines',
            'Icon'     => 'bi bi-arrows-expand',
            'AgeRange' => '6-10',
            'Blurb'    => 'Spot the lever, wheel, ramp or pulley being used in everyday pictures.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Forces & Motion',
            'Slug'     => 'forces-motion',
            'Icon'     => 'bi bi-arrow-right',
            'AgeRange' => '10-13',
            'Blurb'    => 'Calculate speed from distance and time in simple everyday scenarios.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Circuits',
            'Slug'     => 'circuits',
            'Icon'     => 'bi bi-lightning-charge',
            'AgeRange' => '10-13',
            'Blurb'    => 'Build a simple circuit and tell series circuits apart from parallel ones.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Energy Transfers',
            'Slug'     => 'energy-transfers',
            'Icon'     => 'bi bi-graph-up',
            'AgeRange' => '10-13',
            'Blurb'    => 'Match everyday scenarios to the energy transfer taking place.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Waves',
            'Slug'     => 'waves',
            'Icon'     => 'bi bi-symmetry-vertical',
            'AgeRange' => '10-13',
            'Blurb'    => 'Label the parts of a wave — amplitude, wavelength and frequency.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Space & Orbits',
            'Slug'     => 'space-orbits',
            'Icon'     => 'bi bi-globe2',
            'AgeRange' => '10-13',
            'Blurb'    => 'Put the planets in order and match facts about our solar system.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Forces & Newton\'s Laws',
            'Slug'     => 'forces-newtons-laws',
            'Icon'     => 'bi bi-calculator',
            'AgeRange' => '13-16',
            'Blurb'    => 'Calculate force, mass and acceleration using F = ma.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Electricity Calculations',
            'Slug'     => 'electricity-calculations',
            'Icon'     => 'bi bi-hash',
            'AgeRange' => '13-16',
            'Blurb'    => 'Practise voltage, current and resistance calculations using V = IR.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Energy & Work Done',
            'Slug'     => 'energy-work-done',
            'Icon'     => 'bi bi-arrow-up-circle',
            'AgeRange' => '13-16',
            'Blurb'    => 'Work out work done, gravitational potential energy and kinetic energy.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Waves & Radiation',
            'Slug'     => 'waves-radiation',
            'Icon'     => 'bi bi-signpost-split',
            'AgeRange' => '13-16',
            'Blurb'    => 'Order the electromagnetic spectrum and practise wave speed calculations.',
        ], [
            'Category' => 'Physics',
            'Name'     => 'Momentum & Motion Graphs',
            'Slug'     => 'momentum-motion-graphs',
            'Icon'     => 'bi bi-graph-up',
            'AgeRange' => '13-16',
            'Blurb'    => 'Read distance-time and velocity-time graphs to answer motion questions.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Day & Night',
            'Slug'     => 'day-night',
            'Icon'     => 'bi bi-arrow-repeat',
            'AgeRange' => '6-10',
            'Blurb'    => 'See why we get day and night as the Earth spins, and answer questions on it.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Seasons',
            'Slug'     => 'seasons',
            'Icon'     => 'bi bi-calendar3',
            'AgeRange' => '6-10',
            'Blurb'    => 'Match each season to the right weather and clothing.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Weather Watch',
            'Slug'     => 'weather-watch',
            'Icon'     => 'bi bi-droplet-half',
            'AgeRange' => '6-10',
            'Blurb'    => 'Sort weather symbols into sunny, rainy, snowy and windy.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Our Solar System',
            'Slug'     => 'our-solar-system',
            'Icon'     => 'bi bi-globe2',
            'AgeRange' => '6-10',
            'Blurb'    => 'Match the planets to their order out from the Sun.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Rocks & Soil',
            'Slug'     => 'rocks-soil',
            'Icon'     => 'bi bi-box-seam',
            'AgeRange' => '6-10',
            'Blurb'    => 'Sort different rocks and soils by how they look and feel.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'The Water Cycle',
            'Slug'     => 'water-cycle',
            'Icon'     => 'bi bi-arrow-repeat',
            'AgeRange' => '10-13',
            'Blurb'    => 'Put the stages of the water cycle — evaporation, condensation and precipitation — in order.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Rock Cycle',
            'Slug'     => 'rock-cycle',
            'Icon'     => 'bi bi-arrow-clockwise',
            'AgeRange' => '10-13',
            'Blurb'    => 'Identify igneous, sedimentary and metamorphic rocks and how they form.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Solar System Facts',
            'Slug'     => 'solar-system-facts',
            'Icon'     => 'bi bi-globe2',
            'AgeRange' => '10-13',
            'Blurb'    => 'Match planet facts — size, distance from the Sun and number of moons.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Moon Phases',
            'Slug'     => 'moon-phases',
            'Icon'     => 'bi bi-circle',
            'AgeRange' => '10-13',
            'Blurb'    => 'Put the phases of the Moon in the correct order.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Weather & Climate',
            'Slug'     => 'weather-climate',
            'Icon'     => 'bi bi-graph-up',
            'AgeRange' => '10-13',
            'Blurb'    => 'Read simple weather data and climate graphs to answer questions.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Plate Tectonics',
            'Slug'     => 'plate-tectonics',
            'Icon'     => 'bi bi-arrows-collapse',
            'AgeRange' => '13-16',
            'Blurb'    => 'Match plate boundary types to the earthquakes, volcanoes or mountains they cause.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'The Carbon Cycle',
            'Slug'     => 'carbon-cycle',
            'Icon'     => 'bi bi-arrow-repeat',
            'AgeRange' => '13-16',
            'Blurb'    => 'Label and order the stages of the carbon cycle.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Climate Change',
            'Slug'     => 'climate-change',
            'Icon'     => 'bi bi-exclamation-triangle-fill',
            'AgeRange' => '13-16',
            'Blurb'    => 'Interpret climate data and answer questions on the greenhouse effect.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Stellar Evolution',
            'Slug'     => 'stellar-evolution',
            'Icon'     => 'bi bi-star-fill',
            'AgeRange' => '13-16',
            'Blurb'    => 'Put the life cycle of a star in the correct order, from nebula to its final stage.',
        ], [
            'Category' => 'Earth & Space',
            'Name'     => 'Universe Scale',
            'Slug'     => 'universe-scale',
            'Icon'     => 'bi bi-arrows-expand',
            'AgeRange' => '13-16',
            'Blurb'    => 'Order objects by size and distance — planet, star, galaxy and universe.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Lab Safety',
            'Slug'     => 'lab-safety',
            'Icon'     => 'bi bi-shield-check',
            'AgeRange' => '6-10',
            'Blurb'    => 'Spot the safe and unsafe things to do when doing a science experiment.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Five Senses',
            'Slug'     => 'five-senses',
            'Icon'     => 'bi bi-eye',
            'AgeRange' => '6-10',
            'Blurb'    => 'Match an observation to the sense used to make it — sight, sound, smell, taste or touch.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Sorting & Grouping',
            'Slug'     => 'sorting-grouping',
            'Icon'     => 'bi bi-collection',
            'AgeRange' => '6-10',
            'Blurb'    => 'Group objects by a property such as colour, size or material.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Measuring Basics',
            'Slug'     => 'measuring-basics',
            'Icon'     => 'bi bi-rulers',
            'AgeRange' => '6-10',
            'Blurb'    => 'Read a simple scale on a ruler, jug or thermometer.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Fair Test Spotter',
            'Slug'     => 'fair-test-spotter',
            'Icon'     => 'bi bi-question-circle',
            'AgeRange' => '6-10',
            'Blurb'    => 'Spot what makes a simple experiment fair — or what has gone wrong.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Reading Scales',
            'Slug'     => 'reading-scales',
            'Icon'     => 'bi bi-sliders',
            'AgeRange' => '10-13',
            'Blurb'    => 'Read values from rulers, thermometers, measuring cylinders and force meters.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Variables Game',
            'Slug'     => 'variables-game',
            'Icon'     => 'bi bi-list-check',
            'AgeRange' => '10-13',
            'Blurb'    => 'Identify the independent, dependent and control variables in an experiment.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Graph Builder',
            'Slug'     => 'graph-builder',
            'Icon'     => 'bi bi-graph-up',
            'AgeRange' => '10-13',
            'Blurb'    => 'Plot and read simple line and bar graphs from a set of results.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Equipment Match',
            'Slug'     => 'equipment-match',
            'Icon'     => 'bi bi-clipboard',
            'AgeRange' => '10-13',
            'Blurb'    => 'Match each piece of lab equipment to what it is used for.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Scientific Method',
            'Slug'     => 'scientific-method',
            'Icon'     => 'bi bi-list-ol',
            'AgeRange' => '10-13',
            'Blurb'    => 'Put the steps of a science investigation into the right order.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Data Analysis',
            'Slug'     => 'data-analysis',
            'Icon'     => 'bi bi-table',
            'AgeRange' => '13-16',
            'Blurb'    => 'Calculate the mean, spot anomalies, and describe trends in a set of results.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Practical Techniques',
            'Slug'     => 'practical-techniques',
            'Icon'     => 'bi bi-funnel',
            'AgeRange' => '13-16',
            'Blurb'    => 'Put the steps of a required practical — such as titration or microscopy — in order.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Evaluating Experiments',
            'Slug'     => 'evaluating-experiments',
            'Icon'     => 'bi bi-exclamation-triangle-fill',
            'AgeRange' => '13-16',
            'Blurb'    => 'Spot sources of error in an experiment and suggest how to improve it.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Significant Figures & Units',
            'Slug'     => 'significant-figures-units',
            'Icon'     => 'bi bi-hash',
            'AgeRange' => '13-16',
            'Blurb'    => 'Practise rounding to significant figures and using the right units in your answer.',
        ], [
            'Category' => 'Science Lab',
            'Name'     => 'Graph Interpretation',
            'Slug'     => 'graph-interpretation',
            'Icon'     => 'bi bi-graph-up',
            'AgeRange' => '13-16',
            'Blurb'    => 'Calculate the gradient of a line graph and interpret what it shows.',
        ]];

        foreach ($games as $game) {
            Game::create([
                'sort_order'     => $game['SortOrder'] ?? null,
                'age_range_slug' => Str::slug($game['AgeRange']),
                'category_slug'  => Str::slug($game['Category']),
                'slug'           => $game['Slug'] ?? Str::slug($game['Name']),
                'name'           => $game['Name'],
                'icon'           => $game['Icon'],
                'blurb'          => $game['Blurb'],
            ]);
        }
    }
}
